version: "3.9"
services:
  tmpstore:
    #build: .
    image: ghcr.io/hoshinoneko/yatfhs:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
    environment:
      - TZ=UTC
